### PR TITLE
Use `removeAll` for Swift 5 and O(n) filter for Swift < 4.2

### PR DESCRIPTION
**Pull request by ApolloZhu**
Although `index(of:)` has been renamed to `firstIndex(of:)` in Swift 5, `removeAll` should work for Swift 5 and previous versions of Swift as well.

### CODE REVIEW

**Comment by onevcat** [comment]
@ApolloZhu Thanks for it. Since we may still want to support Swift 4 for a while, can you add a compilation condition for Swift compiler or language version to make it work for both versions?

**Comment by ApolloZhu** [comment]
Sorry that I didn't realize removeAll(where:) was only introduced since Swift 4.2.

The old implementation looks like O(n^2) to me (O(n) for look up and O(n) for removing elements). Do you think this O(n) approach would be better?

```swift
styles = styles.filter { $0 != style }
```

Cons: [fresh memory allocation and a copy of all the elements in full even if none need to be removed.](https://github.com/apple/swift-evolution/blob/master/proposals/0197-remove-where.md)

**Comment by onevcat** [comment]
Sure! 😂 This code was written for a long time ago. `filter` is much better than the current implementation. Maybe we need to find some time to make all them better!

**Comment by ApolloZhu** [comment]
Is there anything else I should do?

**Comment by onevcat** [comment]
Sorry I just didn't get the notification!

**Pull request merged**
