### PR TITLE
[WIP] Swift 3.0

### PR DESCRIPTION
**Pull request by onevcat**

### CODE REVIEW

**Comment by iluuu1994** [comment]
@onevcat Can you maybe create a pre-release tag for this branch so we can use it through the Swift Package Manager? 🙏

**Comment by onevcat** [comment]
@iluuu1994 Sure. I will add a tag to it.

**Comment by onevcat** [comment]
@iluuu1994 2.0.0-alpha.1 is added. Hope it could help.

**Comment by iluuu1994** [comment]
@onevcat Awesomeness! Thanks man!

**Comment by ahyattdev** [comment]
Great work!

**Pull request merged**
