### PR TITLE
Updated for Swift 3.0 per 2016-05-09 development snapshot.

### PR DESCRIPTION
**Pull request by FredLoh**
Updated code to work with Swift 3.0-dev 2016-05-09 development snapshot.  There should be a 3.0 public release candidate coming up in the next few weeks, might want to merge then (since this will probably break all 2.2 builds).

Would also love some feedback, this is my first contribution to open source 🔥

### CODE REVIEW

**Comment by ahyattdev** [comment]
This is great! 

Coincidentally, I was just looking for a Swift 3.0 version of this library an hour ago. Thank you for updating it while maintaining Swift 2 compatibility!

**Comment by onevcat** [comment]
@FredLoh Cool. Thanks for this!

I will take a look at it later and then merge it when Swift 3.0 published.

Good job.

**Comment by FredLoh** [comment]
@onevcat Sounds good.  I wasn't sure what the best practice for the #if was so if it was a small amount of lines I did it inside the function if not I redeclared the whole thing. Let me know if thats not the standard /(what you'd like) and I can fix it up.

**Comment by onevcat** [comment]
And I think it will be totally OK to remove the Swift 2.2 legacy code. These changes definitely reserve to a major version update, so users could keep using an earlier version if they choose to leave in Swift 2.2. 

It is more important to keep the code base clean than back compatibility, especially for such upgrade. I have created a new branch called "swift-3.0", could you revert the last commit for back compatibility and then send another p-r to that branch? Then we could merge it now and then find a good timing to release that branch.

Thanks again!

**Comment by onevcat** [comment]
And we also need to do some work to adopt to the new Swift API naming convention (eg. renaming the `extractModesForString(string:)` to something like `extractModes(string:)`, as well as make the enum member lowercase). 

I am not sure whether there could be a migrator for this. I guess we could do it later when Xcode 8 beta coming out to save some time :)

**Comment by FredLoh** [comment]
I can take a look at that later this week. The only major difference (other than naming) that I saw when I transitioned the code was in OutputTarget line 35 where the new code is force unwrapping.  Not sure what your thoughts are on that.

**Pull request closed without merging**
