### PR TITLE
I did not check, but maybe this will fix the SPM

### PR DESCRIPTION
**Pull request by nerzh**
maybe fix SPM

### CODE REVIEW

**Comment by onevcat** [comment]
@nerzh Thanks for the PR. But may I know what is the issue now?

I tried to add Rainbow through SPM in my mac and it seems everything is just working fine for the current released version.

Did you encounter any problem? Are there any reproducible steps for it?

**Comment by nerzh** [comment]
oh...) I do not know english, but I will try to explain)
After add Rainbow to package.json, SPM looking for folder with tour module Rainbow inside the Source folder. If directory Source/Rainbow does not exist, then the import will not have module Rainbow, maybe )

**Comment by onevcat** [comment]
> After add Rainbow to package.json

Maybe you meant the `Package.swift` file instead of `package.json`?

And after adding the Rainbow in the dependency list, you also need to add it to your target. Here is a working `Package.swift`, can you try it?

```swift
// swift-tools-version:5.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "MyApp",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/onevcat/Rainbow.git", from: "3.0.0")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "MyApp",
            dependencies: ["Rainbow"]),  // <---- You also need to add the `Rainbow` here.
        .testTarget(
            name: "MyAppTests",
            dependencies: ["MyApp"]),
    ]
)
```

**Comment by nerzh** [comment]
:D Sorry, yes, I means Package.swift )

**Comment by nerzh** [comment]
then with you example inside MyApp, import Rainbow it impossible

**Comment by nerzh** [comment]
hm, now I tried create simple Linux project and this works fine. But inside framework for ios with your folders structure the "import Rainbow" is not work

**Comment by nerzh** [comment]
I cleaned the xcode project (cmd + shift + k) and the error disappeared... Close. Thanks for answer

**Pull request closed without merging**
